# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

# theme = "blowfish"
baseURL = "https://MalaZedik.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 0

buildDrafts = false
buildFuture = false

googleAnalytics = "G-W469RKPYMY"

[imaging]
  anchor = 'Center'

[taxonomies]
#  tag = "tags"
  category = "categories"
#  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
